"""Typer-based CLI for commitforge."""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from pathlib import Path

import typer

from commitforge.analyzer import analyze_changes, get_checklist, suggest_commit
from commitforge.config import create_default_config, load_config
from commitforge.scanner import scan_repo
from commitforge.types import ScanResult
from commitforge.utils import _log
from commitforge.validator import validate_commit_message

app = typer.Typer(
    name="commitforge",
    help="Repository analysis and commit standardization tool.",
    add_completion=False,
)


def _find_git_root(start: Path) -> Path | None:
    """Walk up from *start* to find the git repository root.

    Args:
        start: Directory to start searching from.

    Returns:
        Path to git root, or None if not found.
    """
    current = start.resolve()
    while True:
        if (current / ".git").is_dir():
            return current
        parent = current.parent
        if parent == current:
            return None
        current = parent


def _safe_load_config(repo_root: Path) -> "Config | None":
    """Load config, exiting with code 2 on failure."""
    from commitforge.types import Config

    try:
        return load_config(repo_root)
    except Exception as exc:
        _log(f"Failed to load config: {exc}", logging.ERROR)
        typer.echo(f"Error: {exc}", err=True)
        raise typer.Exit(2)


def _generate_md_report(
    repo_root: Path, scan_result: ScanResult, config: "Config"
) -> str:
    """Generate a Markdown report from scan results."""
    from commitforge.types import Config

    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    counts: dict[str, int] = {}
    for f in scan_result.findings:
        counts[f.severity] = counts.get(f.severity, 0) + 1

    lines = [
        "# CommitForge Scan Report",
        "",
        f"**Generated:** {ts}",
        f"**Repository:** {repo_root.resolve()}",
        f"**Files scanned:** {scan_result.files_scanned}",
        f"**Changes found:** {len(scan_result.findings)}",
        "",
        "## Summary",
        "",
    ]

    for level in ("critical", "warning", "info"):
        count = counts.get(level, 0)
        if count:
            lines.append(f"- **{level.upper()}:** {count}")
    lines.append("")

    if scan_result.thresholds_exceeded:
        lines.append(
            "> **WARNING:** Severity thresholds exceeded. "
            "Review findings before committing."
        )
        lines.append("")

    lines += ["## Findings", ""]

    if scan_result.findings:
        lines.append(
            "| Severity | File | Details |"
        )
        lines.append(
            "|----------|------|---------|"
        )
        for f in scan_result.findings:
            lines.append(
                f"| {f.severity.upper()} | `{f.path}` | {f.message} |"
            )
    else:
        lines.append("No changes detected.")

    lines.append("")
    lines.append(
        "---"
    )
    lines.append(
        "*Generated by [CommitForge](https://github.com/your-org/commitforge)*"
    )
    lines.append("")

    return "\n".join(lines)


def _generate_html_report(
    repo_root: Path, scan_result: ScanResult, config: "Config"
) -> str:
    """Generate an HTML report from scan results."""
    from commitforge.types import Config

    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    counts: dict[str, int] = {}
    for f in scan_result.findings:
        counts[f.severity] = counts.get(f.severity, 0) + 1

    severity_colors = {
        "critical": "#dc3545",
        "warning": "#fd7e14",
        "info": "#6c757d",
    }

    rows = ""
    for f in scan_result.findings:
        color = severity_colors.get(f.severity, "#6c757d")
        rows += (
            f'<tr>'
            f'<td><span style="color:{color};font-weight:bold">'
            f'{f.severity.upper()}</span></td>'
            f'<td><code>{f.path}</code></td>'
            f'<td>{f.message}</td>'
            f'</tr>\n'
        )

    summary_items = ""
    for level in ("critical", "warning", "info"):
        count = counts.get(level, 0)
        if count:
            color = severity_colors.get(level, "#6c757d")
            summary_items += (
                f'<li style="color:{color};font-weight:bold">'
                f'{level.upper()}: {count}</li>\n'
            )

    warning_banner = ""
    if scan_result.thresholds_exceeded:
        warning_banner = (
            '<div style="background:#fff3cd;color:#856404;'
            'padding:12px;border-radius:4px;margin-bottom:20px;'
            'border:1px solid #ffc107">'
            '<strong>WARNING:</strong> Severity thresholds exceeded. '
            'Review findings before committing.'
            '</div>'
        )

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>CommitForge Scan Report</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI",
    Roboto, sans-serif; max-width: 900px; margin: 40px auto;
    padding: 0 20px; color: #333; }}
  h1 {{ border-bottom: 2px solid #eee; padding-bottom: 10px; }}
  table {{ border-collapse: collapse; width: 100%; margin: 20px 0; }}
  th, td {{ text-align: left; padding: 10px 12px;
    border-bottom: 1px solid #eee; }}
  th {{ background: #f8f9fa; }}
  code {{ background: #f1f3f5; padding: 2px 6px; border-radius: 3px;
    font-size: 0.9em; }}
  .meta {{ color: #666; font-size: 0.95em; }}
  ul {{ list-style: none; padding: 0; }}
  ul li {{ padding: 4px 0; }}
  footer {{ margin-top: 40px; padding-top: 15px;
    border-top: 1px solid #eee; color: #999; font-size: 0.85em; }}
</style>
</head>
<body>
<h1>CommitForge Scan Report</h1>
<p class="meta">
  <strong>Generated:</strong> {ts}<br>
  <strong>Repository:</strong> {repo_root.resolve()}<br>
  <strong>Files scanned:</strong> {scan_result.files_scanned}<br>
  <strong>Changes found:</strong> {len(scan_result.findings)}
</p>

<h2>Summary</h2>
<ul>{summary_items}</ul>

{warning_banner}

<h2>Findings</h2>
<table>
  <thead>
    <tr><th>Severity</th><th>File</th><th>Details</th></tr>
  </thead>
  <tbody>
{rows}  </tbody>
</table>

<footer>
  Generated by <a href="https://github.com/your-org/commitforge">
  CommitForge</a>
</footer>
</body>
</html>"""
    return html


def _write_report(
    repo_root: Path,
    scan_result: ScanResult,
    config: "Config",
    report_path: Path,
) -> None:
    """Write scan report to file, auto-detecting format from extension."""
    from commitforge.types import Config

    ext = report_path.suffix.lower()
    if ext == ".html":
        content = _generate_html_report(repo_root, scan_result, config)
    elif ext == ".md":
        content = _generate_md_report(repo_root, scan_result, config)
    else:
        typer.echo(
            f"Error: Unsupported report format '{ext}'. "
            "Use .md or .html",
            err=True,
        )
        raise typer.Exit(2)

    try:
        report_path.write_text(content, encoding="utf-8")
        typer.echo(f"Report written to: {report_path}")
    except PermissionError as exc:
        typer.echo(f"Error: Cannot write report: {exc}", err=True)
        raise typer.Exit(2)


@app.command()
def init(repo_root: Path = typer.Argument(
    Path("."), help="Path to the repository root."
)) -> None:
    """Create a default .commitforge.json configuration file."""
    if not repo_root.is_dir():
        typer.echo(f"Error: '{repo_root}' is not a directory.", err=True)
        raise typer.Exit(2)
    try:
        create_default_config(repo_root)
        typer.echo(f"Config created at: {repo_root / '.commitforge.json'}")
    except Exception as exc:
        _log(f"Failed to create config: {exc}", logging.ERROR)
        typer.echo(f"Error: {exc}", err=True)
        raise typer.Exit(2)


@app.command()
def scan(
    repo_root: Path = typer.Argument(
        Path("."), help="Path to the repository root."
    ),
    verbose: bool = typer.Option(
        False, "--verbose", "-v", help="Show detailed findings."
    ),
    report: str | None = typer.Option(
        None,
        "--report",
        "-r",
        help="Export findings to a report file (.md or .html).",
    ),
) -> None:
    """Scan the repository and print findings."""
    # Auto-detect git root if user passed "."
    if repo_root == Path("."):
        detected = _find_git_root(Path.cwd())
        if detected:
            repo_root = detected

    config = _safe_load_config(repo_root)
    scan_result = scan_repo(repo_root, config)
    scan_result = analyze_changes(repo_root, config, scan_result)

    if not scan_result.findings:
        typer.echo("No changes detected.")
        if report:
            _write_report(repo_root, scan_result, config, Path(report))
        return

    # Count by severity
    counts: dict[str, int] = {}
    for f in scan_result.findings:
        counts[f.severity] = counts.get(f.severity, 0) + 1

    typer.echo(f"Files scanned: {scan_result.files_scanned}")
    typer.echo(f"Changes found: {len(scan_result.findings)}")

    if verbose:
        typer.echo("")
        for finding in scan_result.findings:
            loc = finding.path
            if finding.line_number > 0:
                loc += f":{finding.line_number}"
            typer.echo(
                f"  [{finding.severity.upper():8s}] {loc}"
            )
            typer.echo(f"             -> {finding.message}")
        typer.echo("")

    # Summary line
    parts = []
    for level in ("critical", "warning", "info"):
        if level in counts:
            parts.append(f"{counts[level]} {level}")
    typer.echo(f"Summary: {', '.join(parts)}")

    # Pre-commit checklist (only warnings and criticals)
    checklist = get_checklist(scan_result)
    actionable = [(s, l, m) for s, l, m in checklist if s in ("WARNING", "CRITICAL")]
    if actionable:
        typer.echo("")
        typer.echo("Before you commit:")
        for i, (severity, location, message) in enumerate(actionable, 1):
            typer.echo(f"  {i}. [{severity}] {location}: {message}")

    # Write report if requested
    if report:
        _write_report(repo_root, scan_result, config, Path(report))

    if scan_result.thresholds_exceeded:
        typer.echo("")
        typer.echo(
            "WARNING: Severity thresholds exceeded.",
            err=True,
        )
        typer.echo(
            "  Review the findings above before committing.",
            err=True,
        )
        raise typer.Exit(1)


@app.command()
def suggest(
    repo_root: Path = typer.Argument(
        Path("."), help="Path to the repository root."
    ),
    scope: str | None = typer.Option(
        None, "--scope", "-s", help="Commit scope (e.g., 'core', 'api')."
    ),
    breaking: bool = typer.Option(
        False, "--breaking", "-b", help="Mark as a breaking change."
    ),
) -> None:
    """Generate a conventional commit suggestion."""
    # Auto-detect git root if user passed "."
    if repo_root == Path("."):
        detected = _find_git_root(Path.cwd())
        if detected:
            repo_root = detected

    config = _safe_load_config(repo_root)
    scan_result = scan_repo(repo_root, config)
    scan_result = analyze_changes(repo_root, config, scan_result)

    suggestion = suggest_commit(
        config, scan_result=scan_result, scope=scope, breaking=breaking
    )
    typer.echo(str(suggestion))


@app.command()
def validate(
    message: str = typer.Argument(..., help="The commit message to validate."),
    repo_root: Path = typer.Argument(
        Path("."), help="Path to the repository root (for config)."
    ),
) -> None:
    """Validate a commit message against Conventional Commit rules."""
    config = _safe_load_config(repo_root)
    is_valid, violations = validate_commit_message(message, config)
    if is_valid:
        typer.echo("Commit message is valid.")
    else:
        typer.echo("Commit message has errors:")
        for v in violations:
            typer.echo(f"  - {v}")
        raise typer.Exit(1)


@app.command()
def status(
    repo_root: Path = typer.Argument(
        Path("."), help="Path to the repository root."
    ),
) -> None:
    """Show a quick summary of the current configuration and scan state."""
    # Auto-detect git root if user passed "."
    if repo_root == Path("."):
        detected = _find_git_root(Path.cwd())
        if detected:
            repo_root = detected

    config = _safe_load_config(repo_root)
    typer.echo("=== CommitForge Status ===")
    typer.echo(f"Ignored paths: {len(config.ignore_paths)}")
    typer.echo(f"Max file size: {config.max_file_size_mb} MB")
    typer.echo(f"Severity thresholds: {config.severity_thresholds}")
    typer.echo(f"Commit mappings: {len(config.commit_mappings)} types")
    scan_result = scan_repo(repo_root, config)
    typer.echo(f"Files scanned: {scan_result.files_scanned}")


def main() -> None:
    """Entry point for the CLI."""
    app()


if __name__ == "__main__":
    main()
